/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cassie_leg_ankle_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[35] = {3, 8, 0, 3, 6, 9, 12, 15, 18, 21, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* cassie_leg_ankle:(i0[8],i1[8])->(o0[3],o1[3x8],o2[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a6, a7, a8, a9;
  a0=-4.9000000000000002e-02;
  a1=8.9999999999999997e-02;
  a2=-4.4408920985006262e-16;
  a3=arg[0]? arg[0][0] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a6=(a1*a5);
  a0=(a0+a6);
  a6=1.2000000000000000e-01;
  a7=arg[0]? arg[0][1] : 0;
  a8=cos(a7);
  a9=(a2*a8);
  a10=(a5*a9);
  a3=sin(a3);
  a11=(a2*a3);
  a12=sin(a7);
  a13=(a11*a12);
  a13=(a8-a13);
  a10=(a10+a13);
  a13=4.8966386501092529e-12;
  a14=arg[0]? arg[0][2] : 0;
  a15=cos(a14);
  a16=(a13*a15);
  a17=sin(a14);
  a16=(a16+a17);
  a18=(a10*a16);
  a19=(a2-a5);
  a20=4.8965831389580217e-12;
  a21=(a20*a17);
  a21=(a21-a15);
  a22=(a19*a21);
  a23=(a2*a12);
  a5=(a5*a23);
  a11=(a11*a8);
  a11=(a11+a12);
  a5=(a5+a11);
  a11=5.5511151231257827e-17;
  a24=(a11*a15);
  a25=(a13*a17);
  a24=(a24+a25);
  a25=(a5*a24);
  a22=(a22-a25);
  a18=(a18+a22);
  a22=(a6*a18);
  a25=4.4999999999999997e-03;
  a26=(a20*a10);
  a26=(a26+a5);
  a27=(a25*a26);
  a22=(a22+a27);
  a22=(a0+a22);
  a27=6.0679999999999998e-02;
  a28=arg[0]? arg[0][3] : 0;
  a29=cos(a28);
  a30=(a18*a29);
  a31=(a13*a17);
  a31=(a15-a31);
  a10=(a10*a31);
  a32=(a20*a15);
  a32=(a17+a32);
  a33=(a19*a32);
  a15=(a13*a15);
  a17=(a11*a17);
  a15=(a15-a17);
  a5=(a5*a15);
  a33=(a33-a5);
  a10=(a10+a33);
  a33=sin(a28);
  a5=(a10*a33);
  a30=(a30+a5);
  a5=(a27*a30);
  a17=4.7410000000000001e-02;
  a10=(a10*a29);
  a18=(a18*a33);
  a10=(a10-a18);
  a18=(a17*a10);
  a5=(a5+a18);
  a5=(a22+a5);
  a18=4.3475999999999998e-01;
  a34=arg[0]? arg[0][4] : 0;
  a35=cos(a34);
  a36=(a30*a35);
  a37=sin(a34);
  a38=(a10*a37);
  a36=(a36+a38);
  a38=(a18*a36);
  a39=2.0000000000000000e-02;
  a10=(a10*a35);
  a30=(a30*a37);
  a10=(a10-a30);
  a30=(a39*a10);
  a38=(a38+a30);
  a38=(a5+a38);
  a30=4.0799999999999997e-01;
  a40=arg[0]? arg[0][5] : 0;
  a41=cos(a40);
  a42=(a36*a41);
  a43=sin(a40);
  a44=(a10*a43);
  a42=(a42+a44);
  a44=(a30*a42);
  a45=-4.0000000000000001e-02;
  a10=(a10*a41);
  a36=(a36*a43);
  a10=(a10-a36);
  a36=(a45*a10);
  a44=(a44+a36);
  a44=(a38+a44);
  if (res[0]!=0) res[0][0]=a44;
  a36=1.3500000000000001e-01;
  a46=(a1*a3);
  a36=(a36+a46);
  a46=(a3*a9);
  a47=(a4*a12);
  a46=(a46+a47);
  a47=(a46*a16);
  a48=(a4*a8);
  a49=(a3*a23);
  a48=(a48-a49);
  a49=(a48*a24);
  a50=(a3*a21);
  a49=(a49-a50);
  a47=(a47+a49);
  a49=(a6*a47);
  a50=(a20*a46);
  a50=(a50-a48);
  a51=(a25*a50);
  a49=(a49+a51);
  a49=(a36+a49);
  a51=(a47*a29);
  a46=(a46*a31);
  a48=(a48*a15);
  a52=(a3*a32);
  a48=(a48-a52);
  a46=(a46+a48);
  a48=(a46*a33);
  a51=(a51+a48);
  a48=(a27*a51);
  a46=(a46*a29);
  a47=(a47*a33);
  a46=(a46-a47);
  a47=(a17*a46);
  a48=(a48+a47);
  a48=(a49+a48);
  a47=(a51*a35);
  a52=(a46*a37);
  a47=(a47+a52);
  a52=(a18*a47);
  a46=(a46*a35);
  a51=(a51*a37);
  a46=(a46-a51);
  a51=(a39*a46);
  a52=(a52+a51);
  a52=(a48+a52);
  a51=(a47*a41);
  a53=(a46*a43);
  a51=(a51+a53);
  a53=(a30*a51);
  a46=(a46*a41);
  a47=(a47*a43);
  a46=(a46-a47);
  a47=(a45*a46);
  a53=(a53+a47);
  a53=(a52+a53);
  if (res[0]!=0) res[0][1]=a53;
  a47=(a3*a12);
  a54=(a2*a8);
  a47=(a47+a54);
  a9=(a4*a9);
  a47=(a47-a9);
  a16=(a47*a16);
  a23=(a4*a23);
  a8=(a3*a8);
  a12=(a2*a12);
  a8=(a8-a12);
  a23=(a23+a8);
  a24=(a23*a24);
  a8=1.9721522630525295e-31;
  a8=(a4+a8);
  a21=(a8*a21);
  a24=(a24+a21);
  a16=(a16+a24);
  a24=(a6*a16);
  a21=(a20*a47);
  a21=(a21-a23);
  a12=(a25*a21);
  a24=(a24+a12);
  a4=(a1*a4);
  a24=(a24-a4);
  a12=(a16*a29);
  a47=(a47*a31);
  a23=(a23*a15);
  a32=(a8*a32);
  a23=(a23+a32);
  a47=(a47+a23);
  a23=(a47*a33);
  a12=(a12+a23);
  a23=(a27*a12);
  a47=(a47*a29);
  a16=(a16*a33);
  a47=(a47-a16);
  a16=(a17*a47);
  a23=(a23+a16);
  a23=(a24+a23);
  a16=(a12*a35);
  a33=(a47*a37);
  a16=(a16+a33);
  a33=(a18*a16);
  a47=(a47*a35);
  a12=(a12*a37);
  a47=(a47-a12);
  a12=(a39*a47);
  a33=(a33+a12);
  a33=(a23+a33);
  a12=(a16*a41);
  a37=(a47*a43);
  a12=(a12+a37);
  a37=(a30*a12);
  a47=(a47*a41);
  a16=(a16*a43);
  a47=(a47-a16);
  a16=(a45*a47);
  a37=(a37+a16);
  a37=(a33+a37);
  if (res[0]!=0) res[0][2]=a37;
  a16=-5.9952043329758457e-17;
  a43=(a2*a53);
  a16=(a16-a43);
  if (res[1]!=0) res[1][0]=a16;
  a16=-2.1760371282653069e-17;
  a43=(a2*a44);
  a43=(a37-a43);
  a16=(a16-a43);
  if (res[1]!=0) res[1][1]=a16;
  a16=-1.3500000000000001e-01;
  a16=(a16+a53);
  if (res[1]!=0) res[1][2]=a16;
  a16=(a36*a8);
  a43=(a4*a3);
  a16=(a16-a43);
  a43=(a53*a8);
  a41=(a37*a3);
  a43=(a43+a41);
  a16=(a16-a43);
  if (res[1]!=0) res[1][3]=a16;
  a16=(a4*a19);
  a43=(a0*a8);
  a16=(a16+a43);
  a43=(a37*a19);
  a8=(a44*a8);
  a43=(a43-a8);
  a16=(a16+a43);
  a16=(-a16);
  if (res[1]!=0) res[1][4]=a16;
  a16=(a44*a3);
  a43=(a53*a19);
  a16=(a16+a43);
  a3=(a0*a3);
  a19=(a36*a19);
  a3=(a3+a19);
  a16=(a16-a3);
  if (res[1]!=0) res[1][5]=a16;
  a16=(a36*a21);
  a3=(a4*a50);
  a16=(a16+a3);
  a3=(a53*a21);
  a19=(a37*a50);
  a3=(a3-a19);
  a16=(a16-a3);
  if (res[1]!=0) res[1][6]=a16;
  a4=(a4*a26);
  a16=(a0*a21);
  a4=(a4+a16);
  a16=(a37*a26);
  a3=(a44*a21);
  a16=(a16-a3);
  a4=(a4+a16);
  a4=(-a4);
  if (res[1]!=0) res[1][7]=a4;
  a0=(a0*a50);
  a36=(a36*a26);
  a0=(a0-a36);
  a36=(a44*a50);
  a4=(a53*a26);
  a36=(a36-a4);
  a0=(a0-a36);
  if (res[1]!=0) res[1][8]=a0;
  a0=(a49*a21);
  a36=(a24*a50);
  a0=(a0-a36);
  a36=(a53*a21);
  a4=(a37*a50);
  a36=(a36-a4);
  a0=(a0-a36);
  if (res[1]!=0) res[1][9]=a0;
  a24=(a24*a26);
  a0=(a22*a21);
  a24=(a24-a0);
  a0=(a37*a26);
  a36=(a44*a21);
  a0=(a0-a36);
  a24=(a24-a0);
  if (res[1]!=0) res[1][10]=a24;
  a22=(a22*a50);
  a49=(a49*a26);
  a22=(a22-a49);
  a49=(a44*a50);
  a24=(a53*a26);
  a49=(a49-a24);
  a22=(a22-a49);
  if (res[1]!=0) res[1][11]=a22;
  a22=(a48*a21);
  a49=(a23*a50);
  a22=(a22-a49);
  a49=(a53*a21);
  a24=(a37*a50);
  a49=(a49-a24);
  a22=(a22-a49);
  if (res[1]!=0) res[1][12]=a22;
  a23=(a23*a26);
  a22=(a5*a21);
  a23=(a23-a22);
  a22=(a37*a26);
  a49=(a44*a21);
  a22=(a22-a49);
  a23=(a23-a22);
  if (res[1]!=0) res[1][13]=a23;
  a5=(a5*a50);
  a48=(a48*a26);
  a5=(a5-a48);
  a48=(a44*a50);
  a23=(a53*a26);
  a48=(a48-a23);
  a5=(a5-a48);
  if (res[1]!=0) res[1][14]=a5;
  a5=(a52*a21);
  a48=(a33*a50);
  a5=(a5-a48);
  a48=(a53*a21);
  a23=(a37*a50);
  a48=(a48-a23);
  a5=(a5-a48);
  if (res[1]!=0) res[1][15]=a5;
  a33=(a33*a26);
  a5=(a38*a21);
  a33=(a33-a5);
  a5=(a37*a26);
  a48=(a44*a21);
  a5=(a5-a48);
  a33=(a33-a5);
  if (res[1]!=0) res[1][16]=a33;
  a38=(a38*a50);
  a52=(a52*a26);
  a38=(a38-a52);
  a52=(a44*a50);
  a33=(a53*a26);
  a52=(a52-a33);
  a38=(a38-a52);
  if (res[1]!=0) res[1][17]=a38;
  a38=0.;
  if (res[1]!=0) res[1][18]=a38;
  if (res[1]!=0) res[1][19]=a38;
  if (res[1]!=0) res[1][20]=a38;
  a38=(a53*a21);
  a52=(a37*a50);
  a38=(a38-a52);
  a52=(a53*a21);
  a33=(a37*a50);
  a52=(a52-a33);
  a38=(a38-a52);
  if (res[1]!=0) res[1][21]=a38;
  a38=(a37*a26);
  a52=(a44*a21);
  a38=(a38-a52);
  a37=(a37*a26);
  a52=(a44*a21);
  a37=(a37-a52);
  a38=(a38-a37);
  if (res[1]!=0) res[1][22]=a38;
  a38=(a44*a50);
  a37=(a53*a26);
  a38=(a38-a37);
  a44=(a44*a50);
  a53=(a53*a26);
  a44=(a44-a53);
  a38=(a38-a44);
  if (res[1]!=0) res[1][23]=a38;
  a38=arg[0]? arg[0][7] : 0;
  a44=cos(a38);
  a53=(a42*a44);
  a37=sin(a38);
  a52=(a10*a37);
  a53=(a53+a52);
  a52=arg[1]? arg[1][7] : 0;
  a33=cos(a38);
  a5=cos(a40);
  a48=cos(a34);
  a23=cos(a28);
  a22=cos(a14);
  a14=sin(a14);
  a49=(a13*a14);
  a49=(a22-a49);
  a24=sin(a7);
  a0=arg[1]? arg[1][0] : 0;
  a1=(a1*a0);
  a36=(a24*a1);
  a4=(a49*a36);
  a16=(a13*a22);
  a3=(a11*a14);
  a16=(a16-a3);
  a7=cos(a7);
  a1=(a7*a1);
  a3=(a16*a1);
  a4=(a4+a3);
  a3=(a13*a22);
  a3=(a3+a14);
  a7=(a7*a0);
  a19=(a3*a7);
  a43=(a20*a14);
  a43=(a43-a22);
  a8=arg[1]? arg[1][1] : 0;
  a2=(a2*a0);
  a2=(a8+a2);
  a43=(a43*a2);
  a11=(a11*a22);
  a13=(a13*a14);
  a11=(a11+a13);
  a24=(a24*a0);
  a0=(a11*a24);
  a43=(a43-a0);
  a19=(a19+a43);
  a43=(a25*a19);
  a0=arg[1]? arg[1][2] : 0;
  a13=(a20*a7);
  a13=(a13+a24);
  a13=(a0+a13);
  a41=(a6*a13);
  a43=(a43-a41);
  a43=(a4-a43);
  a41=(a23*a43);
  a28=sin(a28);
  a35=(a3*a36);
  a29=(a11*a1);
  a35=(a35+a29);
  a29=(a49*a7);
  a22=(a20*a22);
  a14=(a14+a22);
  a14=(a14*a2);
  a2=(a16*a24);
  a14=(a14-a2);
  a29=(a29+a14);
  a14=(a25*a29);
  a14=(a35+a14);
  a2=(a28*a14);
  a41=(a41-a2);
  a2=arg[1]? arg[1][3] : 0;
  a13=(a2+a13);
  a22=(a27*a13);
  a22=(a41+a22);
  a32=(a48*a22);
  a34=sin(a34);
  a14=(a23*a14);
  a43=(a28*a43);
  a14=(a14+a43);
  a43=(a17*a13);
  a43=(a14-a43);
  a15=(a34*a43);
  a32=(a32-a15);
  a15=arg[1]? arg[1][4] : 0;
  a13=(a15+a13);
  a31=(a18*a13);
  a31=(a32+a31);
  a9=(a5*a31);
  a40=sin(a40);
  a43=(a48*a43);
  a22=(a34*a22);
  a43=(a43+a22);
  a22=(a39*a13);
  a22=(a43-a22);
  a54=(a40*a22);
  a9=(a9-a54);
  a54=arg[1]? arg[1][5] : 0;
  a13=(a54+a13);
  a55=(a30*a13);
  a55=(a9+a55);
  a56=(a33*a55);
  a38=sin(a38);
  a22=(a5*a22);
  a31=(a40*a31);
  a22=(a22+a31);
  a13=(a45*a13);
  a13=(a22-a13);
  a31=(a38*a13);
  a56=(a56-a31);
  a56=(a52*a56);
  a9=(a54*a9);
  a32=(a15*a32);
  a41=(a2*a41);
  a4=(a0*a4);
  a1=(a8*a1);
  a31=(a3*a1);
  a36=(a8*a36);
  a57=(a11*a36);
  a31=(a31-a57);
  a4=(a4+a31);
  a31=(a0*a19);
  a24=(a8*a24);
  a57=(a49*a24);
  a8=(a8*a7);
  a7=(a16*a8);
  a57=(a57+a7);
  a31=(a31+a57);
  a57=(a25*a31);
  a4=(a4-a57);
  a57=(a23*a4);
  a49=(a49*a1);
  a16=(a16*a36);
  a49=(a49-a16);
  a35=(a0*a35);
  a49=(a49-a35);
  a0=(a0*a29);
  a3=(a3*a24);
  a11=(a11*a8);
  a3=(a3+a11);
  a0=(a0-a3);
  a25=(a25*a0);
  a24=(a20*a24);
  a8=(a8-a24);
  a24=(a6*a8);
  a25=(a25-a24);
  a49=(a49-a25);
  a25=(a28*a49);
  a57=(a57+a25);
  a41=(a41+a57);
  a57=(a17*a8);
  a41=(a41-a57);
  a57=(a48*a41);
  a49=(a23*a49);
  a4=(a28*a4);
  a49=(a49-a4);
  a14=(a2*a14);
  a49=(a49-a14);
  a14=(a27*a8);
  a49=(a49+a14);
  a14=(a34*a49);
  a57=(a57+a14);
  a32=(a32+a57);
  a57=(a39*a8);
  a32=(a32-a57);
  a57=(a5*a32);
  a49=(a48*a49);
  a41=(a34*a41);
  a49=(a49-a41);
  a43=(a15*a43);
  a49=(a49-a43);
  a43=(a18*a8);
  a49=(a49+a43);
  a43=(a40*a49);
  a57=(a57+a43);
  a9=(a9+a57);
  a57=(a45*a8);
  a9=(a9-a57);
  a57=(a33*a9);
  a49=(a5*a49);
  a32=(a40*a32);
  a49=(a49-a32);
  a22=(a54*a22);
  a49=(a49-a22);
  a8=(a30*a8);
  a49=(a49+a8);
  a8=(a38*a49);
  a57=(a57+a8);
  a56=(a56+a57);
  a53=(a53*a56);
  a10=(a10*a44);
  a42=(a42*a37);
  a10=(a10-a42);
  a49=(a33*a49);
  a9=(a38*a9);
  a49=(a49-a9);
  a33=(a33*a13);
  a38=(a38*a55);
  a33=(a33+a38);
  a52=(a52*a33);
  a49=(a49-a52);
  a10=(a10*a49);
  a20=(a20*a1);
  a20=(a20+a36);
  a6=(a6*a31);
  a20=(a20+a6);
  a6=(a23*a19);
  a36=(a28*a29);
  a6=(a6+a36);
  a36=(a2*a6);
  a1=(a28*a0);
  a52=(a23*a31);
  a1=(a1+a52);
  a36=(a36+a1);
  a27=(a27*a36);
  a29=(a23*a29);
  a19=(a28*a19);
  a29=(a29-a19);
  a2=(a2*a29);
  a23=(a23*a0);
  a28=(a28*a31);
  a23=(a23-a28);
  a2=(a2+a23);
  a17=(a17*a2);
  a27=(a27+a17);
  a20=(a20+a27);
  a27=(a48*a6);
  a17=(a34*a29);
  a27=(a27+a17);
  a17=(a15*a27);
  a23=(a34*a2);
  a28=(a48*a36);
  a23=(a23+a28);
  a17=(a17+a23);
  a18=(a18*a17);
  a29=(a48*a29);
  a6=(a34*a6);
  a29=(a29-a6);
  a15=(a15*a29);
  a48=(a48*a2);
  a34=(a34*a36);
  a48=(a48-a34);
  a15=(a15+a48);
  a39=(a39*a15);
  a18=(a18+a39);
  a20=(a20+a18);
  a18=(a5*a27);
  a39=(a40*a29);
  a18=(a18+a39);
  a18=(a54*a18);
  a39=(a40*a15);
  a48=(a5*a17);
  a39=(a39+a48);
  a18=(a18+a39);
  a30=(a30*a18);
  a29=(a5*a29);
  a27=(a40*a27);
  a29=(a29-a27);
  a54=(a54*a29);
  a5=(a5*a15);
  a40=(a40*a17);
  a5=(a5-a40);
  a54=(a54+a5);
  a45=(a45*a54);
  a30=(a30+a45);
  a20=(a20+a30);
  a26=(a26*a20);
  a10=(a10+a26);
  a53=(a53+a10);
  if (res[2]!=0) res[2][0]=a53;
  a53=(a51*a44);
  a10=(a46*a37);
  a53=(a53+a10);
  a53=(a53*a56);
  a46=(a46*a44);
  a51=(a51*a37);
  a46=(a46-a51);
  a46=(a46*a49);
  a50=(a50*a20);
  a46=(a46+a50);
  a53=(a53+a46);
  if (res[2]!=0) res[2][1]=a53;
  a53=(a12*a44);
  a46=(a47*a37);
  a53=(a53+a46);
  a53=(a53*a56);
  a47=(a47*a44);
  a12=(a12*a37);
  a47=(a47-a12);
  a47=(a47*a49);
  a21=(a21*a20);
  a47=(a47+a21);
  a53=(a53+a47);
  if (res[2]!=0) res[2][2]=a53;
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_leg_ankle(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cassie_leg_ankle_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_leg_ankle_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_leg_ankle_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cassie_leg_ankle_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_leg_ankle_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cassie_leg_ankle_incref(void) {
}

CASADI_SYMBOL_EXPORT void cassie_leg_ankle_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cassie_leg_ankle_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cassie_leg_ankle_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cassie_leg_ankle_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_leg_ankle_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_leg_ankle_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_leg_ankle_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_leg_ankle_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cassie_leg_ankle_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
