/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int arm_actuation_matrix(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int arm_actuation_matrix_alloc_mem(void);
int arm_actuation_matrix_init_mem(int mem);
void arm_actuation_matrix_free_mem(int mem);
int arm_actuation_matrix_checkout(void);
void arm_actuation_matrix_release(int mem);
void arm_actuation_matrix_incref(void);
void arm_actuation_matrix_decref(void);
casadi_int arm_actuation_matrix_n_in(void);
casadi_int arm_actuation_matrix_n_out(void);
casadi_real arm_actuation_matrix_default_in(casadi_int i);
const char* arm_actuation_matrix_name_in(casadi_int i);
const char* arm_actuation_matrix_name_out(casadi_int i);
const casadi_int* arm_actuation_matrix_sparsity_in(casadi_int i);
const casadi_int* arm_actuation_matrix_sparsity_out(casadi_int i);
int arm_actuation_matrix_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
