/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int arm_hand(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int arm_hand_alloc_mem(void);
int arm_hand_init_mem(int mem);
void arm_hand_free_mem(int mem);
int arm_hand_checkout(void);
void arm_hand_release(int mem);
void arm_hand_incref(void);
void arm_hand_decref(void);
casadi_int arm_hand_n_in(void);
casadi_int arm_hand_n_out(void);
casadi_real arm_hand_default_in(casadi_int i);
const char* arm_hand_name_in(casadi_int i);
const char* arm_hand_name_out(casadi_int i);
const casadi_int* arm_hand_sparsity_in(casadi_int i);
const casadi_int* arm_hand_sparsity_out(casadi_int i);
int arm_hand_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define arm_hand_SZ_ARG 2
#define arm_hand_SZ_RES 3
#define arm_hand_SZ_IW 0
#define arm_hand_SZ_W 17
#ifdef __cplusplus
} /* extern "C" */
#endif
