/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int arm_constraint(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int arm_constraint_alloc_mem(void);
int arm_constraint_init_mem(int mem);
void arm_constraint_free_mem(int mem);
int arm_constraint_checkout(void);
void arm_constraint_release(int mem);
void arm_constraint_incref(void);
void arm_constraint_decref(void);
casadi_int arm_constraint_n_in(void);
casadi_int arm_constraint_n_out(void);
casadi_real arm_constraint_default_in(casadi_int i);
const char* arm_constraint_name_in(casadi_int i);
const char* arm_constraint_name_out(casadi_int i);
const casadi_int* arm_constraint_sparsity_in(casadi_int i);
const casadi_int* arm_constraint_sparsity_out(casadi_int i);
int arm_constraint_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
