/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cassie_left_ankle_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[27] = {23, 1, 0, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
static const casadi_int casadi_s1[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[91] = {3, 22, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* cassie_left_ankle:(i0[23],i1[22])->(o0[3],o1[3x22],o2[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=-4.9000000000000002e-02;
  a2=1.;
  a3=2.;
  a4=arg[0]? arg[0][4] : 0;
  a5=(a3*a4);
  a6=(a5*a4);
  a7=arg[0]? arg[0][5] : 0;
  a8=(a3*a7);
  a7=(a8*a7);
  a9=(a6+a7);
  a9=(a2-a9);
  a10=(a1*a9);
  a11=1.3500000000000001e-01;
  a12=arg[0]? arg[0][3] : 0;
  a13=(a5*a12);
  a14=arg[0]? arg[0][6] : 0;
  a15=(a8*a14);
  a16=(a13-a15);
  a17=(a11*a16);
  a10=(a10+a17);
  a10=(a0+a10);
  a17=8.9999999999999997e-02;
  a18=-4.4408920985006262e-16;
  a19=arg[0]? arg[0][7] : 0;
  a20=cos(a19);
  a21=(a18*a20);
  a22=(a9*a21);
  a23=sin(a19);
  a24=(a16*a23);
  a25=(a8*a12);
  a5=(a5*a14);
  a26=(a25+a5);
  a27=(a26*a20);
  a24=(a24-a27);
  a22=(a22+a24);
  a24=(a17*a22);
  a24=(a10+a24);
  a27=1.2000000000000000e-01;
  a28=arg[0]? arg[0][8] : 0;
  a29=cos(a28);
  a30=(a18*a29);
  a31=(a22*a30);
  a32=(a16*a20);
  a33=(a26*a23);
  a32=(a32+a33);
  a33=(a18*a23);
  a34=(a9*a33);
  a32=(a32-a34);
  a34=sin(a28);
  a35=(a32*a34);
  a36=(a18*a26);
  a36=(a9+a36);
  a37=(a36*a29);
  a35=(a35+a37);
  a31=(a31+a35);
  a35=4.8966386501092529e-12;
  a37=arg[0]? arg[0][9] : 0;
  a38=cos(a37);
  a39=(a35*a38);
  a40=sin(a37);
  a39=(a39+a40);
  a41=(a31*a39);
  a32=(a32*a29);
  a42=(a36*a34);
  a32=(a32-a42);
  a42=(a18*a34);
  a43=(a22*a42);
  a32=(a32-a43);
  a43=5.5511151231257827e-17;
  a44=(a43*a38);
  a45=(a35*a40);
  a44=(a44+a45);
  a45=(a32*a44);
  a46=(a18*a36);
  a46=(a46-a22);
  a22=4.8965831389580217e-12;
  a47=(a22*a40);
  a47=(a47-a38);
  a48=(a46*a47);
  a45=(a45+a48);
  a41=(a41+a45);
  a45=(a27*a41);
  a48=4.4999999999999997e-03;
  a49=(a22*a31);
  a49=(a49-a32);
  a50=(a48*a49);
  a45=(a45+a50);
  a45=(a24+a45);
  a50=6.0679999999999998e-02;
  a51=arg[0]? arg[0][10] : 0;
  a52=cos(a51);
  a53=(a41*a52);
  a54=(a35*a40);
  a54=(a38-a54);
  a31=(a31*a54);
  a55=(a35*a38);
  a56=(a43*a40);
  a55=(a55-a56);
  a32=(a32*a55);
  a38=(a22*a38);
  a40=(a40+a38);
  a38=(a46*a40);
  a32=(a32+a38);
  a31=(a31+a32);
  a32=sin(a51);
  a38=(a31*a32);
  a53=(a53+a38);
  a38=(a50*a53);
  a56=4.7410000000000001e-02;
  a31=(a31*a52);
  a41=(a41*a32);
  a31=(a31-a41);
  a41=(a56*a31);
  a38=(a38+a41);
  a38=(a45+a38);
  a41=4.3475999999999998e-01;
  a57=arg[0]? arg[0][11] : 0;
  a58=cos(a57);
  a59=(a53*a58);
  a60=sin(a57);
  a61=(a31*a60);
  a59=(a59+a61);
  a61=(a41*a59);
  a62=2.0000000000000000e-02;
  a31=(a31*a58);
  a53=(a53*a60);
  a31=(a31-a53);
  a53=(a62*a31);
  a61=(a61+a53);
  a61=(a38+a61);
  a53=4.0799999999999997e-01;
  a63=arg[0]? arg[0][12] : 0;
  a64=cos(a63);
  a65=(a59*a64);
  a66=sin(a63);
  a67=(a31*a66);
  a65=(a65+a67);
  a67=(a53*a65);
  a68=-4.0000000000000001e-02;
  a31=(a31*a64);
  a59=(a59*a66);
  a31=(a31-a59);
  a59=(a68*a31);
  a67=(a67+a59);
  a67=(a61+a67);
  if (res[0]!=0) res[0][0]=a67;
  a59=arg[0]? arg[0][1] : 0;
  a13=(a13+a15);
  a15=(a1*a13);
  a3=(a3*a12);
  a12=(a3*a12);
  a7=(a12+a7);
  a7=(a2-a7);
  a69=(a11*a7);
  a15=(a15+a69);
  a15=(a59+a15);
  a69=(a13*a21);
  a70=(a7*a23);
  a8=(a8*a4);
  a3=(a3*a14);
  a14=(a8-a3);
  a4=(a14*a20);
  a70=(a70-a4);
  a69=(a69+a70);
  a70=(a17*a69);
  a70=(a15+a70);
  a4=(a69*a30);
  a71=(a7*a20);
  a72=(a14*a23);
  a71=(a71+a72);
  a72=(a13*a33);
  a71=(a71-a72);
  a72=(a71*a34);
  a73=(a18*a14);
  a73=(a13+a73);
  a74=(a73*a29);
  a72=(a72+a74);
  a4=(a4+a72);
  a72=(a4*a39);
  a71=(a71*a29);
  a74=(a73*a34);
  a71=(a71-a74);
  a74=(a69*a42);
  a71=(a71-a74);
  a74=(a71*a44);
  a75=(a18*a73);
  a75=(a75-a69);
  a69=(a75*a47);
  a74=(a74+a69);
  a72=(a72+a74);
  a74=(a27*a72);
  a69=(a22*a4);
  a69=(a69-a71);
  a76=(a48*a69);
  a74=(a74+a76);
  a74=(a70+a74);
  a76=(a72*a52);
  a4=(a4*a54);
  a71=(a71*a55);
  a77=(a75*a40);
  a71=(a71+a77);
  a4=(a4+a71);
  a71=(a4*a32);
  a76=(a76+a71);
  a71=(a50*a76);
  a4=(a4*a52);
  a72=(a72*a32);
  a4=(a4-a72);
  a72=(a56*a4);
  a71=(a71+a72);
  a71=(a74+a71);
  a72=(a76*a58);
  a77=(a4*a60);
  a72=(a72+a77);
  a77=(a41*a72);
  a4=(a4*a58);
  a76=(a76*a60);
  a4=(a4-a76);
  a76=(a62*a4);
  a77=(a77+a76);
  a77=(a71+a77);
  a76=(a72*a64);
  a78=(a4*a66);
  a76=(a76+a78);
  a78=(a53*a76);
  a4=(a4*a64);
  a72=(a72*a66);
  a4=(a4-a72);
  a72=(a68*a4);
  a78=(a78+a72);
  a78=(a77+a78);
  if (res[0]!=0) res[0][1]=a78;
  a72=arg[0]? arg[0][2] : 0;
  a25=(a25-a5);
  a5=(a1*a25);
  a8=(a8+a3);
  a3=(a11*a8);
  a5=(a5+a3);
  a5=(a72+a5);
  a21=(a25*a21);
  a3=(a8*a23);
  a12=(a12+a6);
  a2=(a2-a12);
  a12=(a2*a20);
  a3=(a3-a12);
  a21=(a21+a3);
  a3=(a17*a21);
  a3=(a5+a3);
  a30=(a21*a30);
  a20=(a8*a20);
  a23=(a2*a23);
  a20=(a20+a23);
  a33=(a25*a33);
  a20=(a20-a33);
  a33=(a20*a34);
  a23=(a18*a2);
  a23=(a25+a23);
  a12=(a23*a29);
  a33=(a33+a12);
  a30=(a30+a33);
  a39=(a30*a39);
  a20=(a20*a29);
  a34=(a23*a34);
  a20=(a20-a34);
  a42=(a21*a42);
  a20=(a20-a42);
  a44=(a20*a44);
  a42=(a18*a23);
  a42=(a42-a21);
  a47=(a42*a47);
  a44=(a44+a47);
  a39=(a39+a44);
  a44=(a27*a39);
  a47=(a22*a30);
  a47=(a47-a20);
  a21=(a48*a47);
  a44=(a44+a21);
  a44=(a3+a44);
  a21=(a39*a52);
  a30=(a30*a54);
  a20=(a20*a55);
  a40=(a42*a40);
  a20=(a20+a40);
  a30=(a30+a20);
  a20=(a30*a32);
  a21=(a21+a20);
  a20=(a50*a21);
  a30=(a30*a52);
  a39=(a39*a32);
  a30=(a30-a39);
  a39=(a56*a30);
  a20=(a20+a39);
  a20=(a44+a20);
  a39=(a21*a58);
  a32=(a30*a60);
  a39=(a39+a32);
  a32=(a41*a39);
  a30=(a30*a58);
  a21=(a21*a60);
  a30=(a30-a21);
  a21=(a62*a30);
  a32=(a32+a21);
  a32=(a20+a32);
  a21=(a39*a64);
  a60=(a30*a66);
  a21=(a21+a60);
  a60=(a53*a21);
  a30=(a30*a64);
  a39=(a39*a66);
  a30=(a30-a39);
  a39=(a68*a30);
  a60=(a60+a39);
  a60=(a32+a60);
  if (res[0]!=0) res[0][2]=a60;
  if (res[1]!=0) res[1][0]=a9;
  if (res[1]!=0) res[1][1]=a13;
  if (res[1]!=0) res[1][2]=a25;
  if (res[1]!=0) res[1][3]=a16;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a8;
  if (res[1]!=0) res[1][6]=a26;
  if (res[1]!=0) res[1][7]=a14;
  if (res[1]!=0) res[1][8]=a2;
  a39=(a59*a25);
  a66=(a72*a13);
  a39=(a39-a66);
  a66=(a78*a25);
  a64=(a60*a13);
  a66=(a66-a64);
  a39=(a39-a66);
  if (res[1]!=0) res[1][9]=a39;
  a39=(a72*a9);
  a66=(a0*a25);
  a39=(a39-a66);
  a66=(a60*a9);
  a25=(a67*a25);
  a66=(a66-a25);
  a39=(a39-a66);
  if (res[1]!=0) res[1][10]=a39;
  a39=(a0*a13);
  a66=(a59*a9);
  a39=(a39-a66);
  a13=(a67*a13);
  a9=(a78*a9);
  a13=(a13-a9);
  a39=(a39-a13);
  if (res[1]!=0) res[1][11]=a39;
  a39=(a59*a8);
  a13=(a72*a7);
  a39=(a39-a13);
  a13=(a78*a8);
  a9=(a60*a7);
  a13=(a13-a9);
  a39=(a39-a13);
  if (res[1]!=0) res[1][12]=a39;
  a39=(a72*a16);
  a13=(a0*a8);
  a39=(a39-a13);
  a13=(a60*a16);
  a8=(a67*a8);
  a13=(a13-a8);
  a39=(a39-a13);
  if (res[1]!=0) res[1][13]=a39;
  a39=(a0*a7);
  a13=(a59*a16);
  a39=(a39-a13);
  a7=(a67*a7);
  a16=(a78*a16);
  a7=(a7-a16);
  a39=(a39-a7);
  if (res[1]!=0) res[1][14]=a39;
  a39=(a59*a2);
  a7=(a72*a14);
  a39=(a39-a7);
  a7=(a78*a2);
  a16=(a60*a14);
  a7=(a7-a16);
  a39=(a39-a7);
  if (res[1]!=0) res[1][15]=a39;
  a72=(a72*a26);
  a39=(a0*a2);
  a72=(a72-a39);
  a39=(a60*a26);
  a2=(a67*a2);
  a39=(a39-a2);
  a72=(a72-a39);
  if (res[1]!=0) res[1][16]=a72;
  a0=(a0*a14);
  a59=(a59*a26);
  a0=(a0-a59);
  a14=(a67*a14);
  a26=(a78*a26);
  a14=(a14-a26);
  a0=(a0-a14);
  if (res[1]!=0) res[1][17]=a0;
  a0=(a15*a23);
  a14=(a5*a73);
  a0=(a0-a14);
  a14=(a78*a23);
  a26=(a60*a73);
  a14=(a14-a26);
  a0=(a0-a14);
  if (res[1]!=0) res[1][18]=a0;
  a5=(a5*a36);
  a0=(a10*a23);
  a5=(a5-a0);
  a0=(a60*a36);
  a23=(a67*a23);
  a0=(a0-a23);
  a5=(a5-a0);
  if (res[1]!=0) res[1][19]=a5;
  a10=(a10*a73);
  a15=(a15*a36);
  a10=(a10-a15);
  a73=(a67*a73);
  a36=(a78*a36);
  a73=(a73-a36);
  a10=(a10-a73);
  if (res[1]!=0) res[1][20]=a10;
  a10=(a70*a42);
  a73=(a3*a75);
  a10=(a10-a73);
  a73=(a78*a42);
  a36=(a60*a75);
  a73=(a73-a36);
  a10=(a10-a73);
  if (res[1]!=0) res[1][21]=a10;
  a10=(a3*a46);
  a73=(a24*a42);
  a10=(a10-a73);
  a73=(a60*a46);
  a42=(a67*a42);
  a73=(a73-a42);
  a10=(a10-a73);
  if (res[1]!=0) res[1][22]=a10;
  a10=(a24*a75);
  a73=(a70*a46);
  a10=(a10-a73);
  a75=(a67*a75);
  a46=(a78*a46);
  a75=(a75-a46);
  a10=(a10-a75);
  if (res[1]!=0) res[1][23]=a10;
  a10=(a70*a47);
  a75=(a3*a69);
  a10=(a10-a75);
  a75=(a78*a47);
  a46=(a60*a69);
  a75=(a75-a46);
  a10=(a10-a75);
  if (res[1]!=0) res[1][24]=a10;
  a3=(a3*a49);
  a10=(a24*a47);
  a3=(a3-a10);
  a10=(a60*a49);
  a75=(a67*a47);
  a10=(a10-a75);
  a3=(a3-a10);
  if (res[1]!=0) res[1][25]=a3;
  a24=(a24*a69);
  a70=(a70*a49);
  a24=(a24-a70);
  a70=(a67*a69);
  a3=(a78*a49);
  a70=(a70-a3);
  a24=(a24-a70);
  if (res[1]!=0) res[1][26]=a24;
  a24=(a74*a47);
  a70=(a44*a69);
  a24=(a24-a70);
  a70=(a78*a47);
  a3=(a60*a69);
  a70=(a70-a3);
  a24=(a24-a70);
  if (res[1]!=0) res[1][27]=a24;
  a44=(a44*a49);
  a24=(a45*a47);
  a44=(a44-a24);
  a24=(a60*a49);
  a70=(a67*a47);
  a24=(a24-a70);
  a44=(a44-a24);
  if (res[1]!=0) res[1][28]=a44;
  a45=(a45*a69);
  a74=(a74*a49);
  a45=(a45-a74);
  a74=(a67*a69);
  a44=(a78*a49);
  a74=(a74-a44);
  a45=(a45-a74);
  if (res[1]!=0) res[1][29]=a45;
  a45=(a71*a47);
  a74=(a20*a69);
  a45=(a45-a74);
  a74=(a78*a47);
  a44=(a60*a69);
  a74=(a74-a44);
  a45=(a45-a74);
  if (res[1]!=0) res[1][30]=a45;
  a20=(a20*a49);
  a45=(a38*a47);
  a20=(a20-a45);
  a45=(a60*a49);
  a74=(a67*a47);
  a45=(a45-a74);
  a20=(a20-a45);
  if (res[1]!=0) res[1][31]=a20;
  a38=(a38*a69);
  a71=(a71*a49);
  a38=(a38-a71);
  a71=(a67*a69);
  a20=(a78*a49);
  a71=(a71-a20);
  a38=(a38-a71);
  if (res[1]!=0) res[1][32]=a38;
  a38=(a77*a47);
  a71=(a32*a69);
  a38=(a38-a71);
  a71=(a78*a47);
  a20=(a60*a69);
  a71=(a71-a20);
  a38=(a38-a71);
  if (res[1]!=0) res[1][33]=a38;
  a32=(a32*a49);
  a38=(a61*a47);
  a32=(a32-a38);
  a38=(a60*a49);
  a71=(a67*a47);
  a38=(a38-a71);
  a32=(a32-a38);
  if (res[1]!=0) res[1][34]=a32;
  a61=(a61*a69);
  a77=(a77*a49);
  a61=(a61-a77);
  a77=(a67*a69);
  a32=(a78*a49);
  a77=(a77-a32);
  a61=(a61-a77);
  if (res[1]!=0) res[1][35]=a61;
  a61=0.;
  if (res[1]!=0) res[1][36]=a61;
  if (res[1]!=0) res[1][37]=a61;
  if (res[1]!=0) res[1][38]=a61;
  a77=(a78*a47);
  a32=(a60*a69);
  a77=(a77-a32);
  a32=(a78*a47);
  a38=(a60*a69);
  a32=(a32-a38);
  a77=(a77-a32);
  if (res[1]!=0) res[1][39]=a77;
  a77=(a60*a49);
  a32=(a67*a47);
  a77=(a77-a32);
  a60=(a60*a49);
  a32=(a67*a47);
  a60=(a60-a32);
  a77=(a77-a60);
  if (res[1]!=0) res[1][40]=a77;
  a77=(a67*a69);
  a60=(a78*a49);
  a77=(a77-a60);
  a67=(a67*a69);
  a78=(a78*a49);
  a67=(a67-a78);
  a77=(a77-a67);
  if (res[1]!=0) res[1][41]=a77;
  if (res[1]!=0) res[1][42]=a61;
  if (res[1]!=0) res[1][43]=a61;
  if (res[1]!=0) res[1][44]=a61;
  if (res[1]!=0) res[1][45]=a61;
  if (res[1]!=0) res[1][46]=a61;
  if (res[1]!=0) res[1][47]=a61;
  if (res[1]!=0) res[1][48]=a61;
  if (res[1]!=0) res[1][49]=a61;
  if (res[1]!=0) res[1][50]=a61;
  if (res[1]!=0) res[1][51]=a61;
  if (res[1]!=0) res[1][52]=a61;
  if (res[1]!=0) res[1][53]=a61;
  if (res[1]!=0) res[1][54]=a61;
  if (res[1]!=0) res[1][55]=a61;
  if (res[1]!=0) res[1][56]=a61;
  if (res[1]!=0) res[1][57]=a61;
  if (res[1]!=0) res[1][58]=a61;
  if (res[1]!=0) res[1][59]=a61;
  if (res[1]!=0) res[1][60]=a61;
  if (res[1]!=0) res[1][61]=a61;
  if (res[1]!=0) res[1][62]=a61;
  if (res[1]!=0) res[1][63]=a61;
  if (res[1]!=0) res[1][64]=a61;
  if (res[1]!=0) res[1][65]=a61;
  a61=arg[0]? arg[0][14] : 0;
  a77=cos(a61);
  a67=(a65*a77);
  a78=sin(a61);
  a60=(a31*a78);
  a67=(a67+a60);
  a60=arg[1]? arg[1][13] : 0;
  a32=cos(a61);
  a38=cos(a63);
  a71=cos(a57);
  a20=cos(a51);
  a45=cos(a37);
  a37=sin(a37);
  a74=(a35*a37);
  a74=(a45-a74);
  a44=cos(a28);
  a24=(a18*a44);
  a70=cos(a19);
  a3=(a18*a70);
  a10=arg[1]? arg[1][0] : 0;
  a75=arg[1]? arg[1][5] : 0;
  a46=(a11*a75);
  a46=(a10-a46);
  a73=(a3*a46);
  a19=sin(a19);
  a42=arg[1]? arg[1][1] : 0;
  a36=(a1*a75);
  a36=(a42+a36);
  a15=(a19*a36);
  a5=arg[1]? arg[1][2] : 0;
  a0=arg[1]? arg[1][4] : 0;
  a1=(a1*a0);
  a23=arg[1]? arg[1][3] : 0;
  a11=(a11*a23);
  a1=(a1-a11);
  a1=(a5-a1);
  a11=(a70*a1);
  a15=(a15-a11);
  a73=(a73+a15);
  a15=(a24*a73);
  a28=sin(a28);
  a36=(a70*a36);
  a11=(a19*a1);
  a36=(a36+a11);
  a11=(a18*a19);
  a14=(a11*a46);
  a36=(a36-a14);
  a14=arg[1]? arg[1][6] : 0;
  a26=(a18*a75);
  a26=(a23+a26);
  a26=(a14+a26);
  a59=(a17*a26);
  a59=(a36+a59);
  a72=(a28*a59);
  a1=(a18*a1);
  a46=(a46+a1);
  a1=(a70*a0);
  a39=(a19*a75);
  a1=(a1+a39);
  a39=(a11*a23);
  a1=(a1-a39);
  a39=(a17*a1);
  a46=(a46-a39);
  a39=(a44*a46);
  a72=(a72+a39);
  a15=(a15+a72);
  a72=(a74*a15);
  a39=(a35*a45);
  a2=(a43*a37);
  a39=(a39-a2);
  a59=(a44*a59);
  a2=(a28*a46);
  a59=(a59-a2);
  a2=(a18*a28);
  a7=(a2*a73);
  a59=(a59-a7);
  a7=(a39*a59);
  a16=(a22*a45);
  a16=(a37+a16);
  a46=(a18*a46);
  a46=(a46-a73);
  a13=(a16*a46);
  a7=(a7+a13);
  a72=(a72+a7);
  a7=(a35*a45);
  a7=(a7+a37);
  a13=(a3*a23);
  a8=(a19*a0);
  a9=(a70*a75);
  a8=(a8-a9);
  a13=(a13+a8);
  a8=(a24*a13);
  a9=(a28*a1);
  a66=(a44*a26);
  a9=(a9+a66);
  a8=(a8+a9);
  a9=(a7*a8);
  a43=(a43*a45);
  a35=(a35*a37);
  a43=(a43+a35);
  a35=(a44*a1);
  a66=(a28*a26);
  a35=(a35-a66);
  a66=(a2*a13);
  a35=(a35-a66);
  a66=(a43*a35);
  a37=(a22*a37);
  a37=(a37-a45);
  a45=arg[1]? arg[1][7] : 0;
  a26=(a18*a26);
  a26=(a26-a13);
  a26=(a45+a26);
  a25=(a37*a26);
  a66=(a66+a25);
  a9=(a9+a66);
  a66=(a48*a9);
  a25=arg[1]? arg[1][8] : 0;
  a64=(a22*a8);
  a64=(a64-a35);
  a64=(a25+a64);
  a58=(a27*a64);
  a66=(a66-a58);
  a66=(a72-a66);
  a58=(a20*a66);
  a51=sin(a51);
  a52=(a7*a15);
  a40=(a43*a59);
  a46=(a37*a46);
  a40=(a40+a46);
  a52=(a52+a40);
  a40=(a74*a8);
  a46=(a39*a35);
  a26=(a16*a26);
  a46=(a46+a26);
  a40=(a40+a46);
  a46=(a48*a40);
  a46=(a52+a46);
  a26=(a51*a46);
  a58=(a58-a26);
  a26=arg[1]? arg[1][9] : 0;
  a64=(a26+a64);
  a55=(a50*a64);
  a55=(a58+a55);
  a54=(a71*a55);
  a57=sin(a57);
  a46=(a20*a46);
  a66=(a51*a66);
  a46=(a46+a66);
  a66=(a56*a64);
  a66=(a46-a66);
  a34=(a57*a66);
  a54=(a54-a34);
  a34=arg[1]? arg[1][10] : 0;
  a64=(a34+a64);
  a29=(a41*a64);
  a29=(a54+a29);
  a33=(a38*a29);
  a63=sin(a63);
  a66=(a71*a66);
  a55=(a57*a55);
  a66=(a66+a55);
  a55=(a62*a64);
  a55=(a66-a55);
  a12=(a63*a55);
  a33=(a33-a12);
  a12=arg[1]? arg[1][11] : 0;
  a64=(a12+a64);
  a6=(a53*a64);
  a6=(a33+a6);
  a79=(a32*a6);
  a61=sin(a61);
  a55=(a38*a55);
  a29=(a63*a29);
  a55=(a55+a29);
  a64=(a68*a64);
  a64=(a55-a64);
  a29=(a61*a64);
  a79=(a79-a29);
  a79=(a60*a79);
  a33=(a12*a33);
  a54=(a34*a54);
  a58=(a26*a58);
  a72=(a25*a72);
  a59=(a45*a59);
  a36=(a14*a36);
  a29=(a42*a75);
  a80=(a5*a0);
  a29=(a29-a80);
  a80=(a0*a5);
  a81=(a75*a42);
  a80=(a80-a81);
  a29=(a29+a80);
  a3=(a3*a29);
  a80=(a5*a23);
  a81=(a10*a75);
  a80=(a80-a81);
  a75=(a75*a10);
  a5=(a23*a5);
  a75=(a75-a5);
  a80=(a80+a75);
  a75=(a19*a80);
  a5=(a10*a0);
  a81=(a42*a23);
  a5=(a5-a81);
  a23=(a23*a42);
  a0=(a0*a10);
  a23=(a23-a0);
  a5=(a5+a23);
  a23=(a70*a5);
  a75=(a75-a23);
  a3=(a3+a75);
  a36=(a36+a3);
  a3=(a24*a36);
  a70=(a70*a80);
  a19=(a19*a5);
  a70=(a70+a19);
  a11=(a11*a29);
  a70=(a70-a11);
  a73=(a14*a73);
  a70=(a70-a73);
  a73=(a28*a70);
  a5=(a18*a5);
  a29=(a29+a5);
  a13=(a14*a13);
  a17=(a17*a13);
  a29=(a29+a17);
  a17=(a44*a29);
  a73=(a73+a17);
  a3=(a3+a73);
  a59=(a59+a3);
  a3=(a7*a59);
  a70=(a44*a70);
  a73=(a28*a29);
  a70=(a70-a73);
  a73=(a2*a36);
  a70=(a70-a73);
  a15=(a45*a15);
  a70=(a70-a15);
  a15=(a43*a70);
  a18=(a18*a29);
  a18=(a18-a36);
  a36=(a37*a18);
  a15=(a15+a36);
  a3=(a3+a15);
  a72=(a72+a3);
  a35=(a45*a35);
  a14=(a14*a1);
  a24=(a24*a14);
  a28=(a28*a13);
  a24=(a24-a28);
  a35=(a35+a24);
  a24=(a74*a35);
  a45=(a45*a8);
  a2=(a2*a14);
  a44=(a44*a13);
  a2=(a2+a44);
  a45=(a45+a2);
  a2=(a39*a45);
  a44=(a16*a14);
  a2=(a2+a44);
  a24=(a24-a2);
  a2=(a25*a9);
  a24=(a24-a2);
  a2=(a48*a24);
  a72=(a72+a2);
  a2=(a20*a72);
  a74=(a74*a59);
  a39=(a39*a70);
  a16=(a16*a18);
  a39=(a39+a16);
  a74=(a74+a39);
  a52=(a25*a52);
  a74=(a74-a52);
  a25=(a25*a40);
  a7=(a7*a35);
  a43=(a43*a45);
  a37=(a37*a14);
  a43=(a43+a37);
  a7=(a7-a43);
  a25=(a25+a7);
  a48=(a48*a25);
  a35=(a22*a35);
  a35=(a35+a45);
  a45=(a27*a35);
  a48=(a48-a45);
  a74=(a74-a48);
  a48=(a51*a74);
  a2=(a2+a48);
  a58=(a58+a2);
  a2=(a56*a35);
  a58=(a58-a2);
  a2=(a71*a58);
  a74=(a20*a74);
  a72=(a51*a72);
  a74=(a74-a72);
  a46=(a26*a46);
  a74=(a74-a46);
  a46=(a50*a35);
  a74=(a74+a46);
  a46=(a57*a74);
  a2=(a2+a46);
  a54=(a54+a2);
  a2=(a62*a35);
  a54=(a54-a2);
  a2=(a38*a54);
  a74=(a71*a74);
  a58=(a57*a58);
  a74=(a74-a58);
  a66=(a34*a66);
  a74=(a74-a66);
  a66=(a41*a35);
  a74=(a74+a66);
  a66=(a63*a74);
  a2=(a2+a66);
  a33=(a33+a2);
  a2=(a68*a35);
  a33=(a33-a2);
  a2=(a32*a33);
  a74=(a38*a74);
  a54=(a63*a54);
  a74=(a74-a54);
  a55=(a12*a55);
  a74=(a74-a55);
  a35=(a53*a35);
  a74=(a74+a35);
  a35=(a61*a74);
  a2=(a2+a35);
  a79=(a79+a2);
  a67=(a67*a79);
  a31=(a31*a77);
  a65=(a65*a78);
  a31=(a31-a65);
  a74=(a32*a74);
  a33=(a61*a33);
  a74=(a74-a33);
  a32=(a32*a64);
  a61=(a61*a6);
  a32=(a32+a61);
  a60=(a60*a32);
  a74=(a74-a60);
  a31=(a31*a74);
  a22=(a22*a59);
  a22=(a22-a70);
  a27=(a27*a24);
  a22=(a22-a27);
  a27=(a20*a24);
  a70=(a51*a25);
  a27=(a27-a70);
  a70=(a20*a9);
  a59=(a51*a40);
  a70=(a70+a59);
  a59=(a26*a70);
  a27=(a27-a59);
  a50=(a50*a27);
  a40=(a20*a40);
  a9=(a51*a9);
  a40=(a40-a9);
  a26=(a26*a40);
  a20=(a20*a25);
  a51=(a51*a24);
  a20=(a20+a51);
  a26=(a26+a20);
  a56=(a56*a26);
  a50=(a50-a56);
  a22=(a22-a50);
  a50=(a71*a27);
  a56=(a57*a26);
  a50=(a50-a56);
  a56=(a71*a70);
  a20=(a57*a40);
  a56=(a56+a20);
  a20=(a34*a56);
  a50=(a50-a20);
  a41=(a41*a50);
  a40=(a71*a40);
  a70=(a57*a70);
  a40=(a40-a70);
  a34=(a34*a40);
  a71=(a71*a26);
  a57=(a57*a27);
  a71=(a71+a57);
  a34=(a34+a71);
  a62=(a62*a34);
  a41=(a41-a62);
  a22=(a22-a41);
  a41=(a38*a50);
  a62=(a63*a34);
  a41=(a41-a62);
  a62=(a38*a56);
  a71=(a63*a40);
  a62=(a62+a71);
  a62=(a12*a62);
  a41=(a41-a62);
  a53=(a53*a41);
  a40=(a38*a40);
  a56=(a63*a56);
  a40=(a40-a56);
  a12=(a12*a40);
  a38=(a38*a34);
  a63=(a63*a50);
  a38=(a38+a63);
  a12=(a12+a38);
  a68=(a68*a12);
  a53=(a53-a68);
  a22=(a22-a53);
  a49=(a49*a22);
  a31=(a31+a49);
  a67=(a67+a31);
  if (res[2]!=0) res[2][0]=a67;
  a67=(a76*a77);
  a31=(a4*a78);
  a67=(a67+a31);
  a67=(a67*a79);
  a4=(a4*a77);
  a76=(a76*a78);
  a4=(a4-a76);
  a4=(a4*a74);
  a69=(a69*a22);
  a4=(a4+a69);
  a67=(a67+a4);
  if (res[2]!=0) res[2][1]=a67;
  a67=(a21*a77);
  a4=(a30*a78);
  a67=(a67+a4);
  a67=(a67*a79);
  a30=(a30*a77);
  a21=(a21*a78);
  a30=(a30-a21);
  a30=(a30*a74);
  a47=(a47*a22);
  a30=(a30+a47);
  a67=(a67+a30);
  if (res[2]!=0) res[2][2]=a67;
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_left_ankle(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cassie_left_ankle_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_left_ankle_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_left_ankle_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cassie_left_ankle_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_left_ankle_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cassie_left_ankle_incref(void) {
}

CASADI_SYMBOL_EXPORT void cassie_left_ankle_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cassie_left_ankle_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cassie_left_ankle_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cassie_left_ankle_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_left_ankle_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_left_ankle_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_left_ankle_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_left_ankle_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cassie_left_ankle_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
