/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cassie_left_foot_front_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[67] = {3, 16, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* cassie_left_foot_front:(i0[16],i1[16])->(o0[3],o1[3x16],o2[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a7, a8, a9;
  a0=-4.9000000000000002e-02;
  a1=8.9999999999999997e-02;
  a2=-4.4408920985006262e-16;
  a3=arg[0]? arg[0][0] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a6=(a1*a5);
  a0=(a0+a6);
  a6=1.2000000000000000e-01;
  a7=arg[0]? arg[0][1] : 0;
  a8=cos(a7);
  a9=(a2*a8);
  a10=(a5*a9);
  a11=1.0000000000000002e+00;
  a12=(a11*a8);
  a13=(a11*a12);
  a3=sin(a3);
  a14=(a2*a3);
  a15=sin(a7);
  a16=(a14*a15);
  a13=(a13-a16);
  a10=(a10+a13);
  a13=4.8966386501092529e-12;
  a16=arg[0]? arg[0][2] : 0;
  a17=cos(a16);
  a18=(a13*a17);
  a19=sin(a16);
  a18=(a18+a19);
  a20=(a10*a18);
  a21=-1.0000000000000002e+00;
  a22=(a21*a5);
  a23=-4.4408920985006271e-16;
  a22=(a22+a23);
  a23=4.8965831389580217e-12;
  a24=(a23*a19);
  a24=(a24-a17);
  a25=(a22*a24);
  a26=(a2*a15);
  a5=(a5*a26);
  a14=(a14*a8);
  a27=(a11*a15);
  a28=(a11*a27);
  a14=(a14+a28);
  a5=(a5+a14);
  a14=5.5511151231257827e-17;
  a28=(a14*a17);
  a29=(a13*a19);
  a28=(a28+a29);
  a29=(a5*a28);
  a25=(a25-a29);
  a20=(a20+a25);
  a25=(a6*a20);
  a29=4.4999999999999997e-03;
  a30=(a23*a10);
  a30=(a30+a5);
  a31=(a29*a30);
  a25=(a25+a31);
  a25=(a0+a25);
  a31=6.0679999999999998e-02;
  a32=arg[0]? arg[0][3] : 0;
  a33=cos(a32);
  a34=(a20*a33);
  a35=(a13*a19);
  a35=(a17-a35);
  a10=(a10*a35);
  a36=(a23*a17);
  a36=(a19+a36);
  a37=(a22*a36);
  a17=(a13*a17);
  a19=(a14*a19);
  a17=(a17-a19);
  a5=(a5*a17);
  a37=(a37-a5);
  a10=(a10+a37);
  a37=sin(a32);
  a5=(a10*a37);
  a34=(a34+a5);
  a5=(a31*a34);
  a19=4.7410000000000001e-02;
  a10=(a10*a33);
  a20=(a20*a37);
  a10=(a10-a20);
  a20=(a19*a10);
  a5=(a5+a20);
  a5=(a25+a5);
  a20=4.3475999999999998e-01;
  a38=arg[0]? arg[0][4] : 0;
  a39=cos(a38);
  a40=(a34*a39);
  a41=sin(a38);
  a42=(a10*a41);
  a40=(a40+a42);
  a42=(a20*a40);
  a43=2.0000000000000000e-02;
  a10=(a10*a39);
  a34=(a34*a41);
  a10=(a10-a34);
  a34=(a43*a10);
  a42=(a42+a34);
  a42=(a5+a42);
  a34=4.0799999999999997e-01;
  a44=arg[0]? arg[0][5] : 0;
  a45=cos(a44);
  a46=(a40*a45);
  a47=sin(a44);
  a48=(a10*a47);
  a46=(a46+a48);
  a48=(a34*a46);
  a49=-4.0000000000000001e-02;
  a10=(a10*a45);
  a40=(a40*a47);
  a10=(a10-a40);
  a40=(a49*a10);
  a48=(a48+a40);
  a48=(a42+a48);
  a40=arg[0]? arg[0][7] : 0;
  a50=cos(a40);
  a51=(a46*a50);
  a52=sin(a40);
  a53=(a10*a52);
  a51=(a51+a53);
  a53=(a1*a51);
  a53=(a48+a53);
  if (res[0]!=0) res[0][0]=a53;
  a54=1.3500000000000001e-01;
  a55=(a1*a3);
  a54=(a54+a55);
  a55=(a3*a9);
  a56=(a4*a15);
  a55=(a55+a56);
  a56=(a55*a18);
  a57=(a4*a8);
  a58=(a3*a26);
  a57=(a57-a58);
  a58=(a57*a28);
  a59=(a21*a3);
  a60=(a59*a24);
  a58=(a58+a60);
  a56=(a56+a58);
  a58=(a6*a56);
  a60=(a23*a55);
  a60=(a60-a57);
  a61=(a29*a60);
  a58=(a58+a61);
  a58=(a54+a58);
  a61=(a56*a33);
  a55=(a55*a35);
  a57=(a57*a17);
  a62=(a59*a36);
  a57=(a57+a62);
  a55=(a55+a57);
  a57=(a55*a37);
  a61=(a61+a57);
  a57=(a31*a61);
  a55=(a55*a33);
  a56=(a56*a37);
  a55=(a55-a56);
  a56=(a19*a55);
  a57=(a57+a56);
  a57=(a58+a57);
  a56=(a61*a39);
  a62=(a55*a41);
  a56=(a56+a62);
  a62=(a20*a56);
  a55=(a55*a39);
  a61=(a61*a41);
  a55=(a55-a61);
  a61=(a43*a55);
  a62=(a62+a61);
  a62=(a57+a62);
  a61=(a56*a45);
  a63=(a55*a47);
  a61=(a61+a63);
  a63=(a34*a61);
  a55=(a55*a45);
  a56=(a56*a47);
  a55=(a55-a56);
  a56=(a49*a55);
  a63=(a63+a56);
  a63=(a62+a63);
  a56=(a61*a50);
  a64=(a55*a52);
  a56=(a56+a64);
  a64=(a1*a56);
  a64=(a63+a64);
  if (res[0]!=0) res[0][1]=a64;
  a4=(a21*a4);
  a65=(a1*a4);
  a9=(a4*a9);
  a12=(a2*a12);
  a3=(a21*a3);
  a15=(a3*a15);
  a12=(a12-a15);
  a9=(a9+a12);
  a18=(a9*a18);
  a21=(a21*a4);
  a12=1.9721522630525295e-31;
  a21=(a21+a12);
  a24=(a21*a24);
  a4=(a4*a26);
  a3=(a3*a8);
  a27=(a2*a27);
  a3=(a3+a27);
  a4=(a4+a3);
  a28=(a4*a28);
  a24=(a24-a28);
  a18=(a18+a24);
  a24=(a6*a18);
  a28=(a23*a9);
  a28=(a28+a4);
  a3=(a29*a28);
  a24=(a24+a3);
  a24=(a65+a24);
  a3=(a18*a33);
  a9=(a9*a35);
  a36=(a21*a36);
  a4=(a4*a17);
  a36=(a36-a4);
  a9=(a9+a36);
  a36=(a9*a37);
  a3=(a3+a36);
  a36=(a31*a3);
  a9=(a9*a33);
  a18=(a18*a37);
  a9=(a9-a18);
  a18=(a19*a9);
  a36=(a36+a18);
  a36=(a24+a36);
  a18=(a3*a39);
  a37=(a9*a41);
  a18=(a18+a37);
  a37=(a20*a18);
  a9=(a9*a39);
  a3=(a3*a41);
  a9=(a9-a3);
  a3=(a43*a9);
  a37=(a37+a3);
  a37=(a36+a37);
  a3=(a18*a45);
  a41=(a9*a47);
  a3=(a3+a41);
  a41=(a34*a3);
  a9=(a9*a45);
  a18=(a18*a47);
  a9=(a9-a18);
  a18=(a49*a9);
  a41=(a41+a18);
  a41=(a37+a41);
  a18=(a3*a50);
  a47=(a9*a52);
  a18=(a18+a47);
  a47=(a1*a18);
  a47=(a41+a47);
  if (res[0]!=0) res[0][2]=a47;
  a45=-5.9952043329758457e-17;
  a39=(a2*a64);
  a45=(a45-a39);
  if (res[1]!=0) res[1][0]=a45;
  a45=-2.1760371282653069e-17;
  a39=(a11*a47);
  a33=(a2*a53);
  a39=(a39-a33);
  a45=(a45-a39);
  if (res[1]!=0) res[1][1]=a45;
  a45=-1.3500000000000004e-01;
  a39=(a11*a64);
  a45=(a45+a39);
  if (res[1]!=0) res[1][2]=a45;
  a45=(a54*a21);
  a39=(a65*a59);
  a45=(a45-a39);
  a39=(a64*a21);
  a33=(a47*a59);
  a39=(a39-a33);
  a45=(a45-a39);
  if (res[1]!=0) res[1][3]=a45;
  a45=(a65*a22);
  a39=(a0*a21);
  a45=(a45-a39);
  a39=(a47*a22);
  a21=(a53*a21);
  a39=(a39-a21);
  a45=(a45-a39);
  if (res[1]!=0) res[1][4]=a45;
  a45=(a0*a59);
  a39=(a54*a22);
  a45=(a45-a39);
  a59=(a53*a59);
  a22=(a64*a22);
  a59=(a59-a22);
  a45=(a45-a59);
  if (res[1]!=0) res[1][5]=a45;
  a45=(a54*a28);
  a59=(a65*a60);
  a45=(a45-a59);
  a59=(a64*a28);
  a22=(a47*a60);
  a59=(a59-a22);
  a45=(a45-a59);
  if (res[1]!=0) res[1][6]=a45;
  a65=(a65*a30);
  a45=(a0*a28);
  a65=(a65-a45);
  a45=(a47*a30);
  a59=(a53*a28);
  a45=(a45-a59);
  a65=(a65-a45);
  if (res[1]!=0) res[1][7]=a65;
  a0=(a0*a60);
  a54=(a54*a30);
  a0=(a0-a54);
  a54=(a53*a60);
  a65=(a64*a30);
  a54=(a54-a65);
  a0=(a0-a54);
  if (res[1]!=0) res[1][8]=a0;
  a0=(a58*a28);
  a54=(a24*a60);
  a0=(a0-a54);
  a54=(a64*a28);
  a65=(a47*a60);
  a54=(a54-a65);
  a0=(a0-a54);
  if (res[1]!=0) res[1][9]=a0;
  a24=(a24*a30);
  a0=(a25*a28);
  a24=(a24-a0);
  a0=(a47*a30);
  a54=(a53*a28);
  a0=(a0-a54);
  a24=(a24-a0);
  if (res[1]!=0) res[1][10]=a24;
  a25=(a25*a60);
  a58=(a58*a30);
  a25=(a25-a58);
  a58=(a53*a60);
  a24=(a64*a30);
  a58=(a58-a24);
  a25=(a25-a58);
  if (res[1]!=0) res[1][11]=a25;
  a25=(a57*a28);
  a58=(a36*a60);
  a25=(a25-a58);
  a58=(a64*a28);
  a24=(a47*a60);
  a58=(a58-a24);
  a25=(a25-a58);
  if (res[1]!=0) res[1][12]=a25;
  a36=(a36*a30);
  a25=(a5*a28);
  a36=(a36-a25);
  a25=(a47*a30);
  a58=(a53*a28);
  a25=(a25-a58);
  a36=(a36-a25);
  if (res[1]!=0) res[1][13]=a36;
  a5=(a5*a60);
  a57=(a57*a30);
  a5=(a5-a57);
  a57=(a53*a60);
  a36=(a64*a30);
  a57=(a57-a36);
  a5=(a5-a57);
  if (res[1]!=0) res[1][14]=a5;
  a5=(a62*a28);
  a57=(a37*a60);
  a5=(a5-a57);
  a57=(a64*a28);
  a36=(a47*a60);
  a57=(a57-a36);
  a5=(a5-a57);
  if (res[1]!=0) res[1][15]=a5;
  a37=(a37*a30);
  a5=(a42*a28);
  a37=(a37-a5);
  a5=(a47*a30);
  a57=(a53*a28);
  a5=(a5-a57);
  a37=(a37-a5);
  if (res[1]!=0) res[1][16]=a37;
  a42=(a42*a60);
  a62=(a62*a30);
  a42=(a42-a62);
  a62=(a53*a60);
  a37=(a64*a30);
  a62=(a62-a37);
  a42=(a42-a62);
  if (res[1]!=0) res[1][17]=a42;
  a42=0.;
  if (res[1]!=0) res[1][18]=a42;
  if (res[1]!=0) res[1][19]=a42;
  if (res[1]!=0) res[1][20]=a42;
  a62=(a63*a28);
  a37=(a41*a60);
  a62=(a62-a37);
  a37=(a64*a28);
  a5=(a47*a60);
  a37=(a37-a5);
  a62=(a62-a37);
  if (res[1]!=0) res[1][21]=a62;
  a41=(a41*a30);
  a62=(a48*a28);
  a41=(a41-a62);
  a47=(a47*a30);
  a62=(a53*a28);
  a47=(a47-a62);
  a41=(a41-a47);
  if (res[1]!=0) res[1][22]=a41;
  a48=(a48*a60);
  a63=(a63*a30);
  a48=(a48-a63);
  a53=(a53*a60);
  a64=(a64*a30);
  a53=(a53-a64);
  a48=(a48-a53);
  if (res[1]!=0) res[1][23]=a48;
  if (res[1]!=0) res[1][24]=a42;
  if (res[1]!=0) res[1][25]=a42;
  if (res[1]!=0) res[1][26]=a42;
  if (res[1]!=0) res[1][27]=a42;
  if (res[1]!=0) res[1][28]=a42;
  if (res[1]!=0) res[1][29]=a42;
  if (res[1]!=0) res[1][30]=a42;
  if (res[1]!=0) res[1][31]=a42;
  if (res[1]!=0) res[1][32]=a42;
  if (res[1]!=0) res[1][33]=a42;
  if (res[1]!=0) res[1][34]=a42;
  if (res[1]!=0) res[1][35]=a42;
  if (res[1]!=0) res[1][36]=a42;
  if (res[1]!=0) res[1][37]=a42;
  if (res[1]!=0) res[1][38]=a42;
  if (res[1]!=0) res[1][39]=a42;
  if (res[1]!=0) res[1][40]=a42;
  if (res[1]!=0) res[1][41]=a42;
  if (res[1]!=0) res[1][42]=a42;
  if (res[1]!=0) res[1][43]=a42;
  if (res[1]!=0) res[1][44]=a42;
  if (res[1]!=0) res[1][45]=a42;
  if (res[1]!=0) res[1][46]=a42;
  if (res[1]!=0) res[1][47]=a42;
  a42=arg[1]? arg[1][7] : 0;
  a48=cos(a40);
  a53=cos(a44);
  a64=cos(a38);
  a63=cos(a32);
  a41=cos(a16);
  a16=sin(a16);
  a47=(a13*a16);
  a47=(a41-a47);
  a62=sin(a7);
  a37=arg[1]? arg[1][0] : 0;
  a5=(a1*a37);
  a57=(a62*a5);
  a36=(a47*a57);
  a25=(a13*a41);
  a58=(a14*a16);
  a25=(a25-a58);
  a7=cos(a7);
  a5=(a7*a5);
  a58=(a25*a5);
  a36=(a36+a58);
  a58=(a13*a41);
  a58=(a58+a16);
  a7=(a11*a7);
  a7=(a7*a37);
  a24=(a58*a7);
  a0=(a23*a16);
  a0=(a0-a41);
  a54=arg[1]? arg[1][1] : 0;
  a2=(a2*a37);
  a2=(a54+a2);
  a0=(a0*a2);
  a14=(a14*a41);
  a13=(a13*a16);
  a14=(a14+a13);
  a11=(a11*a62);
  a11=(a11*a37);
  a37=(a14*a11);
  a0=(a0-a37);
  a24=(a24+a0);
  a0=(a29*a24);
  a37=arg[1]? arg[1][2] : 0;
  a62=(a23*a7);
  a62=(a62+a11);
  a62=(a37+a62);
  a13=(a6*a62);
  a0=(a0-a13);
  a0=(a36-a0);
  a13=(a63*a0);
  a32=sin(a32);
  a65=(a58*a57);
  a45=(a14*a5);
  a65=(a65+a45);
  a45=(a47*a7);
  a41=(a23*a41);
  a16=(a16+a41);
  a16=(a16*a2);
  a2=(a25*a11);
  a16=(a16-a2);
  a45=(a45+a16);
  a16=(a29*a45);
  a16=(a65+a16);
  a2=(a32*a16);
  a13=(a13-a2);
  a2=arg[1]? arg[1][3] : 0;
  a62=(a2+a62);
  a41=(a31*a62);
  a41=(a13+a41);
  a59=(a64*a41);
  a38=sin(a38);
  a16=(a63*a16);
  a0=(a32*a0);
  a16=(a16+a0);
  a0=(a19*a62);
  a0=(a16-a0);
  a22=(a38*a0);
  a59=(a59-a22);
  a22=arg[1]? arg[1][4] : 0;
  a62=(a22+a62);
  a39=(a20*a62);
  a39=(a59+a39);
  a21=(a53*a39);
  a44=sin(a44);
  a0=(a64*a0);
  a41=(a38*a41);
  a0=(a0+a41);
  a41=(a43*a62);
  a41=(a0-a41);
  a33=(a44*a41);
  a21=(a21-a33);
  a33=arg[1]? arg[1][5] : 0;
  a62=(a33+a62);
  a4=(a34*a62);
  a4=(a21+a4);
  a17=(a48*a4);
  a40=sin(a40);
  a41=(a53*a41);
  a39=(a44*a39);
  a41=(a41+a39);
  a62=(a49*a62);
  a62=(a41-a62);
  a39=(a40*a62);
  a17=(a17-a39);
  a17=(a42*a17);
  a21=(a33*a21);
  a59=(a22*a59);
  a13=(a2*a13);
  a36=(a37*a36);
  a5=(a54*a5);
  a39=(a58*a5);
  a57=(a54*a57);
  a35=(a14*a57);
  a39=(a39-a35);
  a36=(a36+a39);
  a39=(a37*a24);
  a11=(a54*a11);
  a35=(a47*a11);
  a54=(a54*a7);
  a7=(a25*a54);
  a35=(a35+a7);
  a39=(a39+a35);
  a35=(a29*a39);
  a36=(a36-a35);
  a35=(a63*a36);
  a47=(a47*a5);
  a25=(a25*a57);
  a47=(a47-a25);
  a65=(a37*a65);
  a47=(a47-a65);
  a37=(a37*a45);
  a58=(a58*a11);
  a14=(a14*a54);
  a58=(a58+a14);
  a37=(a37-a58);
  a29=(a29*a37);
  a11=(a23*a11);
  a54=(a54-a11);
  a11=(a6*a54);
  a29=(a29-a11);
  a47=(a47-a29);
  a29=(a32*a47);
  a35=(a35+a29);
  a13=(a13+a35);
  a35=(a19*a54);
  a13=(a13-a35);
  a35=(a64*a13);
  a47=(a63*a47);
  a36=(a32*a36);
  a47=(a47-a36);
  a16=(a2*a16);
  a47=(a47-a16);
  a16=(a31*a54);
  a47=(a47+a16);
  a16=(a38*a47);
  a35=(a35+a16);
  a59=(a59+a35);
  a35=(a43*a54);
  a59=(a59-a35);
  a35=(a53*a59);
  a47=(a64*a47);
  a13=(a38*a13);
  a47=(a47-a13);
  a0=(a22*a0);
  a47=(a47-a0);
  a0=(a20*a54);
  a47=(a47+a0);
  a0=(a44*a47);
  a35=(a35+a0);
  a21=(a21+a35);
  a35=(a49*a54);
  a21=(a21-a35);
  a35=(a48*a21);
  a47=(a53*a47);
  a59=(a44*a59);
  a47=(a47-a59);
  a41=(a33*a41);
  a47=(a47-a41);
  a41=(a34*a54);
  a47=(a47+a41);
  a41=(a40*a47);
  a35=(a35+a41);
  a17=(a17+a35);
  a51=(a51*a17);
  a10=(a10*a50);
  a46=(a46*a52);
  a10=(a10-a46);
  a47=(a48*a47);
  a21=(a40*a21);
  a47=(a47-a21);
  a62=(a48*a62);
  a4=(a40*a4);
  a62=(a62+a4);
  a62=(a42*a62);
  a47=(a47-a62);
  a54=(a1*a54);
  a47=(a47+a54);
  a10=(a10*a47);
  a23=(a23*a5);
  a23=(a23+a57);
  a6=(a6*a39);
  a23=(a23+a6);
  a6=(a63*a24);
  a57=(a32*a45);
  a6=(a6+a57);
  a57=(a2*a6);
  a5=(a32*a37);
  a54=(a63*a39);
  a5=(a5+a54);
  a57=(a57+a5);
  a31=(a31*a57);
  a45=(a63*a45);
  a24=(a32*a24);
  a45=(a45-a24);
  a2=(a2*a45);
  a63=(a63*a37);
  a32=(a32*a39);
  a63=(a63-a32);
  a2=(a2+a63);
  a19=(a19*a2);
  a31=(a31+a19);
  a23=(a23+a31);
  a31=(a64*a6);
  a19=(a38*a45);
  a31=(a31+a19);
  a19=(a22*a31);
  a63=(a38*a2);
  a32=(a64*a57);
  a63=(a63+a32);
  a19=(a19+a63);
  a20=(a20*a19);
  a45=(a64*a45);
  a6=(a38*a6);
  a45=(a45-a6);
  a22=(a22*a45);
  a64=(a64*a2);
  a38=(a38*a57);
  a64=(a64-a38);
  a22=(a22+a64);
  a43=(a43*a22);
  a20=(a20+a43);
  a23=(a23+a20);
  a20=(a53*a31);
  a43=(a44*a45);
  a20=(a20+a43);
  a43=(a33*a20);
  a64=(a44*a22);
  a38=(a53*a19);
  a64=(a64+a38);
  a43=(a43+a64);
  a34=(a34*a43);
  a45=(a53*a45);
  a31=(a44*a31);
  a45=(a45-a31);
  a33=(a33*a45);
  a53=(a53*a22);
  a44=(a44*a19);
  a53=(a53-a44);
  a33=(a33+a53);
  a49=(a49*a33);
  a34=(a34+a49);
  a23=(a23+a34);
  a20=(a48*a20);
  a45=(a40*a45);
  a20=(a20+a45);
  a42=(a42*a20);
  a40=(a40*a33);
  a48=(a48*a43);
  a40=(a40+a48);
  a42=(a42+a40);
  a1=(a1*a42);
  a23=(a23+a1);
  a30=(a30*a23);
  a10=(a10+a30);
  a51=(a51+a10);
  if (res[2]!=0) res[2][0]=a51;
  a56=(a56*a17);
  a55=(a55*a50);
  a61=(a61*a52);
  a55=(a55-a61);
  a55=(a55*a47);
  a60=(a60*a23);
  a55=(a55+a60);
  a56=(a56+a55);
  if (res[2]!=0) res[2][1]=a56;
  a18=(a18*a17);
  a9=(a9*a50);
  a3=(a3*a52);
  a9=(a9-a3);
  a9=(a9*a47);
  a28=(a28*a23);
  a9=(a9+a28);
  a18=(a18+a9);
  if (res[2]!=0) res[2][2]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_left_foot_front(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cassie_left_foot_front_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_left_foot_front_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_left_foot_front_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cassie_left_foot_front_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_left_foot_front_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cassie_left_foot_front_incref(void) {
}

CASADI_SYMBOL_EXPORT void cassie_left_foot_front_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cassie_left_foot_front_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cassie_left_foot_front_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cassie_left_foot_front_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_left_foot_front_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_left_foot_front_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_left_foot_front_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_left_foot_front_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cassie_left_foot_front_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
