/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cassie_fixed_actuation_map_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[173] = {16, 10, 0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* cassie_fixed_actuation_map:(i0[16])->(o0[16x10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=25.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  a2=16.;
  if (res[0]!=0) res[0][34]=a2;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  if (res[0]!=0) res[0][39]=a1;
  if (res[0]!=0) res[0][40]=a1;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a1;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a1;
  if (res[0]!=0) res[0][49]=a1;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a2;
  if (res[0]!=0) res[0][52]=a1;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a1;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a1;
  if (res[0]!=0) res[0][57]=a1;
  if (res[0]!=0) res[0][58]=a1;
  if (res[0]!=0) res[0][59]=a1;
  if (res[0]!=0) res[0][60]=a1;
  if (res[0]!=0) res[0][61]=a1;
  if (res[0]!=0) res[0][62]=a1;
  if (res[0]!=0) res[0][63]=a1;
  if (res[0]!=0) res[0][64]=a1;
  if (res[0]!=0) res[0][65]=a1;
  if (res[0]!=0) res[0][66]=a1;
  if (res[0]!=0) res[0][67]=a1;
  if (res[0]!=0) res[0][68]=a1;
  if (res[0]!=0) res[0][69]=a1;
  if (res[0]!=0) res[0][70]=a1;
  a3=50.;
  if (res[0]!=0) res[0][71]=a3;
  if (res[0]!=0) res[0][72]=a1;
  if (res[0]!=0) res[0][73]=a1;
  if (res[0]!=0) res[0][74]=a1;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a1;
  if (res[0]!=0) res[0][78]=a1;
  if (res[0]!=0) res[0][79]=a1;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a1;
  if (res[0]!=0) res[0][82]=a1;
  if (res[0]!=0) res[0][83]=a1;
  if (res[0]!=0) res[0][84]=a1;
  if (res[0]!=0) res[0][85]=a1;
  if (res[0]!=0) res[0][86]=a1;
  if (res[0]!=0) res[0][87]=a1;
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a1;
  if (res[0]!=0) res[0][90]=a1;
  if (res[0]!=0) res[0][91]=a1;
  if (res[0]!=0) res[0][92]=a1;
  if (res[0]!=0) res[0][93]=a1;
  if (res[0]!=0) res[0][94]=a1;
  if (res[0]!=0) res[0][95]=a1;
  if (res[0]!=0) res[0][96]=a1;
  if (res[0]!=0) res[0][97]=a1;
  if (res[0]!=0) res[0][98]=a1;
  if (res[0]!=0) res[0][99]=a1;
  if (res[0]!=0) res[0][100]=a1;
  if (res[0]!=0) res[0][101]=a1;
  if (res[0]!=0) res[0][102]=a1;
  if (res[0]!=0) res[0][103]=a1;
  if (res[0]!=0) res[0][104]=a1;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a1;
  if (res[0]!=0) res[0][107]=a1;
  if (res[0]!=0) res[0][108]=a1;
  if (res[0]!=0) res[0][109]=a1;
  if (res[0]!=0) res[0][110]=a1;
  if (res[0]!=0) res[0][111]=a1;
  if (res[0]!=0) res[0][112]=a1;
  if (res[0]!=0) res[0][113]=a1;
  if (res[0]!=0) res[0][114]=a1;
  if (res[0]!=0) res[0][115]=a1;
  if (res[0]!=0) res[0][116]=a1;
  if (res[0]!=0) res[0][117]=a1;
  if (res[0]!=0) res[0][118]=a1;
  if (res[0]!=0) res[0][119]=a1;
  if (res[0]!=0) res[0][120]=a1;
  if (res[0]!=0) res[0][121]=a1;
  if (res[0]!=0) res[0][122]=a2;
  if (res[0]!=0) res[0][123]=a1;
  if (res[0]!=0) res[0][124]=a1;
  if (res[0]!=0) res[0][125]=a1;
  if (res[0]!=0) res[0][126]=a1;
  if (res[0]!=0) res[0][127]=a1;
  if (res[0]!=0) res[0][128]=a1;
  if (res[0]!=0) res[0][129]=a1;
  if (res[0]!=0) res[0][130]=a1;
  if (res[0]!=0) res[0][131]=a1;
  if (res[0]!=0) res[0][132]=a1;
  if (res[0]!=0) res[0][133]=a1;
  if (res[0]!=0) res[0][134]=a1;
  if (res[0]!=0) res[0][135]=a1;
  if (res[0]!=0) res[0][136]=a1;
  if (res[0]!=0) res[0][137]=a1;
  if (res[0]!=0) res[0][138]=a1;
  if (res[0]!=0) res[0][139]=a2;
  if (res[0]!=0) res[0][140]=a1;
  if (res[0]!=0) res[0][141]=a1;
  if (res[0]!=0) res[0][142]=a1;
  if (res[0]!=0) res[0][143]=a1;
  if (res[0]!=0) res[0][144]=a1;
  if (res[0]!=0) res[0][145]=a1;
  if (res[0]!=0) res[0][146]=a1;
  if (res[0]!=0) res[0][147]=a1;
  if (res[0]!=0) res[0][148]=a1;
  if (res[0]!=0) res[0][149]=a1;
  if (res[0]!=0) res[0][150]=a1;
  if (res[0]!=0) res[0][151]=a1;
  if (res[0]!=0) res[0][152]=a1;
  if (res[0]!=0) res[0][153]=a1;
  if (res[0]!=0) res[0][154]=a1;
  if (res[0]!=0) res[0][155]=a1;
  if (res[0]!=0) res[0][156]=a1;
  if (res[0]!=0) res[0][157]=a1;
  if (res[0]!=0) res[0][158]=a1;
  if (res[0]!=0) res[0][159]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_fixed_actuation_map(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cassie_fixed_actuation_map_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cassie_fixed_actuation_map_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_fixed_actuation_map_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cassie_fixed_actuation_map_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cassie_fixed_actuation_map_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cassie_fixed_actuation_map_incref(void) {
}

CASADI_SYMBOL_EXPORT void cassie_fixed_actuation_map_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cassie_fixed_actuation_map_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int cassie_fixed_actuation_map_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cassie_fixed_actuation_map_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_fixed_actuation_map_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cassie_fixed_actuation_map_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_fixed_actuation_map_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cassie_fixed_actuation_map_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cassie_fixed_actuation_map_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
