/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int cassie_foot_front(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int cassie_foot_front_alloc_mem(void);
int cassie_foot_front_init_mem(int mem);
void cassie_foot_front_free_mem(int mem);
int cassie_foot_front_checkout(void);
void cassie_foot_front_release(int mem);
void cassie_foot_front_incref(void);
void cassie_foot_front_decref(void);
casadi_int cassie_foot_front_n_in(void);
casadi_int cassie_foot_front_n_out(void);
casadi_real cassie_foot_front_default_in(casadi_int i);
const char* cassie_foot_front_name_in(casadi_int i);
const char* cassie_foot_front_name_out(casadi_int i);
const casadi_int* cassie_foot_front_sparsity_in(casadi_int i);
const casadi_int* cassie_foot_front_sparsity_out(casadi_int i);
int cassie_foot_front_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
